modLoader="javafml" #mandatory
loaderVersion="[${forge_major},)" #mandatory
license="https://github.com/benn1ed/CurseOfDisintegration/blob/1.16.5/LICENSE"
issueTrackerURL="https://github.com/benn1ed/CurseOfDisintegration/issues" #optional

[[mods]] #mandatory
modId="curseofdisintegration" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Curse of Disintegration" #mandatory
updateJSONURL="https://github.com/benn1ed/CurseOfDisintegration/blob/1.16.5/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/curse-of-disintegration" #optional
logoFile="curseofdisintegration.png" #optional
credits="toujourspareil (twitter.com/toujourspareil_) for making icons" #optional
authors="benn1ed" #optional
description='''
CURSE OF DISINTEGRATION
Don't spend too much time under stress, otherwise you may very well find yourself being merged with the void.


Rapid evolution of the human species and their swift leap in technical progress have caused an irreparable disturbance in the universe,
magnifying its tendency towards disorder, ultimately resulting in a new and deadly form of matter being created and spread across space and time.

You have observed that hormone adrenaline, which your body usually produces when you're stressed, forces the space around you
to shrink under the pressure of the new form of matter. You conclude that it seems like this substance is somehow attracted to adrenaline.
The sudden increase of its density though affects you in the not-so-desirable way, as you start experiencing nausea and dizziness,
which intensifies your stress even more. This vicious circle goes on as long as you release adrenaline, but there's a limit...

Your few poor friends have proven your guesses. This substance kills. And it seems like it stops at nothing, not even the best armor in the world
can save you from getting disintegrated. That's how you called it, disintegration, because there's nothing left of you in the process.


Being affected by the sources of your disquiet (mostly hostile to you creatures) increases your level of disintegration.
Once the meter is filled, you don't exist anymore. Shortly after you're out of any danger sources, your disintegration level starts to rapidly fall off.
'''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[${forge_major},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
    