package benn1ed.curseofdisintegration.client;

public enum DisintegrationBarLocation
{
	ABOVE_HEALTH_BAR,
	ABOVE_HUNGER_BAR,
	HOTBAR_LEFT,
	HOTBAR_RIGHT,
	TOP_LEFT,
	TOP_CENTER,
	TOP_RIGHT,
	MIDDLE_LEFT,
	MIDDLE_CENTER,
	MIDDLE_RIGHT,
	BOTTOM_LEFT,
	BOTTOM_RIGHT,
	CUSTOM,
	CUSTOM_SCALED
}